### ISSUE TITLE
Viikko 3, tehtävä 8 (Python)

### ISSUE THREAD

**Issue by jtarvainen** [ohjelmistotuotanto-hy-avoin/ohjelmistotuotanto-hy-avoin.github.io#101]
Onkohan tehtävänannosta jäänyt itse tehtävä pois? :-) Tekstissä todetaan, että testien pitäisi epäonnistua, muttei ohjeisteta korjaamaan niitä.

**Comment by Kaltsoon** [comment]
Ainakin tämä ohjeistus löytyy:

> Toteuta testin käyttämät avainsanat tiedostoon resource.robot. Kun suoritat testit, virheilmoitus kertoo mitä avainsanoja on määrittelemättä

**Comment by jtarvainen** [comment]
Niin joo, aivan. Sori, luin huolimattomasti. Kiitti!
