### ISSUE TITLE
Viikon 4 linkit vie vääriin luentotallenteisiin

### ISSUE THREAD

**Issue by tuukkalai** [ohjelmistotuotanto-hy-avoin/ohjelmistotuotanto-hy-avoin.github.io#82]
Luennon 7 linkki vie luennon **5** (2021) tallenteeseen:
https://github.com/ohjelmistotuotanto-hy-avoin/ohjelmistotuotanto-hy-avoin.github.io/blob/cba47dc0ae086a7be526965271b1c98acd57f8da/_layouts/home.html#L118

---

Luennon 8 linkki vie luennon **6** (2021)  tallenteeseen:
https://github.com/ohjelmistotuotanto-hy-avoin/ohjelmistotuotanto-hy-avoin.github.io/blob/cba47dc0ae086a7be526965271b1c98acd57f8da/_layouts/home.html#L125

**Comment by mluukkai** [comment]
korjattu. pahottelut että huomasin tämän vasta nyt
